# Site settings
title: mrprompt
email: mrprompt@gmail.com
url: https://mrprompt.com.br
description: Este é meu site pessoal e nele você pode me conhecer e alguns dos meus projetos.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: https://mrprompt.com.br

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/mrprompt
  - title: instagram
    url: https://instagram.com/onegaothiago
  - title: linkedin
    url: https://linkedin.com/in/paesthiago

# Build settings
markdown: kramdown
permalink: pretty

projects:
  - title: Meteoros Floripa
    url: https://github.com/mrprompt/meteoros-floripa
    description: Estações de capturas de meteoros em Florianópolis/SC 
    icon: camera

  - title: API da BRAMON 
    url: https://github.com/bramon-org/bramon-api
    description: API da BRAMON - Brazilian Meteor Observation Network - para coleta de dados de meteoros.
    icon: database

  - title: Ponto On-line
    url: https://meuponto.site/
    description: Um sistema de ponto on-line para controle de jornada de trabalho.
    icon: clock-o

  - title: Thiago Paes
    url: https://thiagopaes.dev.br
    description: Meu site profissional, com minhas referências e portfólio.
    icon: user