# Site settings
title: mrprompt
email: mrprompt@gmail.com
url: https://mrprompt.com.br
description: Este é meu site pessoal e nele você pode me conhecer e alguns dos meus projetos.

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: https://mrprompt.com.br

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/mrprompt
  - title: instagram
    url: https://instagram.com/onegaothiago
  - title: linkedin
    url: https://linkedin.com/in/paesthiago

# Build settings
markdown: kramdown
permalink: pretty

projects:
  - title: Cielo
    url: https://github.com/mrprompt/cielo
    description: Um projeto de integração com a API da Cielo.
    language: PHP
  - title: Celesc
    url: https://github.com/mrprompt/Celesc
    description: Integração com a CELESC via troca de arquivos. 
    language: PHP
  - title: CaixaEconomicaFederal
    url: https://github.com/mrprompt/CaixaEconomicaFederal
    description: Geração e Leitura de Arquivos de Remessa CNAB240 - SIGCB para a Caixa Econômica Federal. 
    language: PHP
  - title:  API da BRAMON 
    url: https://github.com/bramon-org/bramon-api
    description:  API da BRAMON 
    language: PHP
  - title: Imóvel Web - SDK
    url: https://github.com/mrprompt/imovelweb-sdk
    description:  SDK de integração com a API da Imóvel Web. 
    language: PHP
  - title: Money
    url: https://github.com/mrprompt/money
    description:  Library to made work with currency and money easy. 
    language: PHP
  - title: Boleto Caixa Econômica Federal
    url: https://github.com/mrprompt/BoletoCaixaEconomicaFederal
    description:  Geração de Boletos e Bloquetos para a Caixa Econômica Federal. 
    language: PHP
  - title: Centercob
    url: https://github.com/mrprompt/Centercob
    description:  Integração com a Centercob por meio de troca de arquivos de remessa. 
    language: PHP
  - title: Boleto Sicoob
    url: https://github.com/mrprompt/BoletoSicoob
    description:  Gerar arquivo de remessa (Cobrança) para o Boleto da Sicoob 
    language: PHP
  - title: Classe Db
    url: https://github.com/mrprompt/Db
    description:  Um meio simples e fácil de acessar bases de dados utilizando PDO e XML 
    language: PHP
